// <auto-generated />
namespace BugTrackerApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AppUserDemoAccountPropertyAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AppUserDemoAccountPropertyAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202108202035262_AppUserDemoAccountPropertyAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
